//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clash_Management_System_Navisworks_Addin.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Dar", ConfigurationName="WebService.ClashServiceSoap")]
    public interface ClashServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/DEBUG_CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DEBUG_CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/DEBUG_CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DEBUG_CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/DEBUG_ThrowExceptionToFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DEBUG_ThrowExceptionToFile();
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/DEBUG_ThrowExceptionToFile", ReplyAction="*")]
        System.Threading.Tasks.Task DEBUG_ThrowExceptionToFileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/DEBUG_FixSearchSetsLogTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DEBUG_FixSearchSetsLogTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/DEBUG_FixSearchSetsLogTable", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DEBUG_FixSearchSetsLogTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/GetProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse GetProjects(string domain, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/GetProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> GetProjectsAsync(string domain, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/SyncSearchSets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse SyncSearchSets(string userTradeAbbr, int clashMatrixId, string[] definedSearchSets);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/SyncSearchSets", ReplyAction="*")]
        System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> SyncSearchSetsAsync(string userTradeAbbr, int clashMatrixId, string[] definedSearchSets);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/GetClashTests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse GetClashTests(int clashMatrixId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/GetClashTests", ReplyAction="*")]
        System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> GetClashTestsAsync(int clashMatrixId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/SyncClashResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse SyncClashResults(int clashMatrixId, Clash_Management_System_Navisworks_Addin.WebService.ClashResultSyncRequest[] updateRequests);
        
        [System.ServiceModel.OperationContractAttribute(Action="Dar/SyncClashResults", ReplyAction="*")]
        System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> SyncClashResultsAsync(int clashMatrixId, Clash_Management_System_Navisworks_Addin.WebService.ClashResultSyncRequest[] updateRequests);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Success))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectsResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SyncSearchSetsResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClashTestsResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Error))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public abstract partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseState stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public enum ResponseState {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ClashPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
                this.RaisePropertyChanged("Z");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ClashResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid guidField;
        
        private string nameField;
        
        private string stateField;
        
        private string approvedByField;
        
        private string approvedTimeField;
        
        private string assignedToField;
        
        private string createdTimeField;
        
        private string descriptionField;
        
        private string commentsField;
        
        private string distanceField;
        
        private ClashPoint clashPointField;
        
        private string item1NameField;
        
        private string item1SourceFileField;
        
        private string item2NameField;
        
        private string item2SourceFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("Guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ApprovedBy {
            get {
                return this.approvedByField;
            }
            set {
                this.approvedByField = value;
                this.RaisePropertyChanged("ApprovedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ApprovedTime {
            get {
                return this.approvedTimeField;
            }
            set {
                this.approvedTimeField = value;
                this.RaisePropertyChanged("ApprovedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AssignedTo {
            get {
                return this.assignedToField;
            }
            set {
                this.assignedToField = value;
                this.RaisePropertyChanged("AssignedTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CreatedTime {
            get {
                return this.createdTimeField;
            }
            set {
                this.createdTimeField = value;
                this.RaisePropertyChanged("CreatedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
                this.RaisePropertyChanged("Comments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
                this.RaisePropertyChanged("Distance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public ClashPoint ClashPoint {
            get {
                return this.clashPointField;
            }
            set {
                this.clashPointField = value;
                this.RaisePropertyChanged("ClashPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Item1Name {
            get {
                return this.item1NameField;
            }
            set {
                this.item1NameField = value;
                this.RaisePropertyChanged("Item1Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Item1SourceFile {
            get {
                return this.item1SourceFileField;
            }
            set {
                this.item1SourceFileField = value;
                this.RaisePropertyChanged("Item1SourceFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Item2Name {
            get {
                return this.item2NameField;
            }
            set {
                this.item2NameField = value;
                this.RaisePropertyChanged("Item2Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Item2SourceFile {
            get {
                return this.item2SourceFileField;
            }
            set {
                this.item2SourceFileField = value;
                this.RaisePropertyChanged("Item2SourceFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ClashResultSyncRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int clashTestIdField;
        
        private ClashResult[] newResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClashTestId {
            get {
                return this.clashTestIdField;
            }
            set {
                this.clashTestIdField = value;
                this.RaisePropertyChanged("ClashTestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ClashResult[] NewResults {
            get {
                return this.newResultsField;
            }
            set {
                this.newResultsField = value;
                this.RaisePropertyChanged("NewResults");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ClashMatrix : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string projectCodeField;
        
        private int templateIdField;
        
        private string templateNameField;
        
        private string addByField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("ProjectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
                this.RaisePropertyChanged("TemplateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TemplateName {
            get {
                return this.templateNameField;
            }
            set {
                this.templateNameField = value;
                this.RaisePropertyChanged("TemplateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AddBy {
            get {
                return this.addByField;
            }
            set {
                this.addByField = value;
                this.RaisePropertyChanged("AddBy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class Project : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private ClashMatrix[] matricesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ClashMatrix[] Matrices {
            get {
                return this.matricesField;
            }
            set {
                this.matricesField = value;
                this.RaisePropertyChanged("Matrices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class SearchSetReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int matrixIdField;
        
        private string messageField;
        
        private ReportType reportTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MatrixId {
            get {
                return this.matrixIdField;
            }
            set {
                this.matrixIdField = value;
                this.RaisePropertyChanged("MatrixId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ReportType ReportType {
            get {
                return this.reportTypeField;
            }
            set {
                this.reportTypeField = value;
                this.RaisePropertyChanged("ReportType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public enum ReportType {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        REMOVE,
        
        /// <remarks/>
        UPDATE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class SearchSetInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int tradeIdField;
        
        private string tradeAbbrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TradeId {
            get {
                return this.tradeIdField;
            }
            set {
                this.tradeIdField = value;
                this.RaisePropertyChanged("TradeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TradeAbbr {
            get {
                return this.tradeAbbrField;
            }
            set {
                this.tradeAbbrField = value;
                this.RaisePropertyChanged("TradeAbbr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class Priority : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ClashTest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string uniqueNameField;
        
        private int typeField;
        
        private string typeNameField;
        
        private int matrixIdField;
        
        private int tradeIdField;
        
        private string tradeCodeField;
        
        private System.Nullable<System.DateTime> addDateField;
        
        private System.Nullable<System.DateTime> lastRunDateField;
        
        private string addedByField;
        
        private string projectCodeField;
        
        private Priority priorityField;
        
        private SearchSetInfo searchSet1Field;
        
        private SearchSetInfo searchSet2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UniqueName {
            get {
                return this.uniqueNameField;
            }
            set {
                this.uniqueNameField = value;
                this.RaisePropertyChanged("UniqueName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
                this.RaisePropertyChanged("TypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int MatrixId {
            get {
                return this.matrixIdField;
            }
            set {
                this.matrixIdField = value;
                this.RaisePropertyChanged("MatrixId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TradeId {
            get {
                return this.tradeIdField;
            }
            set {
                this.tradeIdField = value;
                this.RaisePropertyChanged("TradeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TradeCode {
            get {
                return this.tradeCodeField;
            }
            set {
                this.tradeCodeField = value;
                this.RaisePropertyChanged("TradeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> AddDate {
            get {
                return this.addDateField;
            }
            set {
                this.addDateField = value;
                this.RaisePropertyChanged("AddDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> LastRunDate {
            get {
                return this.lastRunDateField;
            }
            set {
                this.lastRunDateField = value;
                this.RaisePropertyChanged("LastRunDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AddedBy {
            get {
                return this.addedByField;
            }
            set {
                this.addedByField = value;
                this.RaisePropertyChanged("AddedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ProjectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("ProjectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public SearchSetInfo SearchSet1 {
            get {
                return this.searchSet1Field;
            }
            set {
                this.searchSet1Field = value;
                this.RaisePropertyChanged("SearchSet1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public SearchSetInfo SearchSet2 {
            get {
                return this.searchSet2Field;
            }
            set {
                this.searchSet2Field = value;
                this.RaisePropertyChanged("SearchSet2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectsResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SyncSearchSetsResults))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClashTestsResults))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class Success : ServiceResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ProjectsResults : Success {
        
        private Project[] projectsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Project[] Projects {
            get {
                return this.projectsField;
            }
            set {
                this.projectsField = value;
                this.RaisePropertyChanged("Projects");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class SyncSearchSetsResults : Success {
        
        private SearchSetReport[] reportsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SearchSetReport[] Reports {
            get {
                return this.reportsField;
            }
            set {
                this.reportsField = value;
                this.RaisePropertyChanged("Reports");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class ClashTestsResults : Success {
        
        private ClashTest[] clashTestsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ClashTest[] ClashTests {
            get {
                return this.clashTestsField;
            }
            set {
                this.clashTestsField = value;
                this.RaisePropertyChanged("ClashTests");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Dar")]
    public partial class Error : ServiceResponse {
        
        private string meesageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Meesage {
            get {
                return this.meesageField;
            }
            set {
                this.meesageField = value;
                this.RaisePropertyChanged("Meesage");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClashServiceSoapChannel : Clash_Management_System_Navisworks_Addin.WebService.ClashServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClashServiceSoapClient : System.ServiceModel.ClientBase<Clash_Management_System_Navisworks_Addin.WebService.ClashServiceSoap>, Clash_Management_System_Navisworks_Addin.WebService.ClashServiceSoap {
        
        public ClashServiceSoapClient() {
        }
        
        public ClashServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClashServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClashServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClashServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DEBUG_CheckDatabaseConnection() {
            return base.Channel.DEBUG_CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<bool> DEBUG_CheckDatabaseConnectionAsync() {
            return base.Channel.DEBUG_CheckDatabaseConnectionAsync();
        }
        
        public void DEBUG_ThrowExceptionToFile() {
            base.Channel.DEBUG_ThrowExceptionToFile();
        }
        
        public System.Threading.Tasks.Task DEBUG_ThrowExceptionToFileAsync() {
            return base.Channel.DEBUG_ThrowExceptionToFileAsync();
        }
        
        public bool DEBUG_FixSearchSetsLogTable() {
            return base.Channel.DEBUG_FixSearchSetsLogTable();
        }
        
        public System.Threading.Tasks.Task<bool> DEBUG_FixSearchSetsLogTableAsync() {
            return base.Channel.DEBUG_FixSearchSetsLogTableAsync();
        }
        
        public Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse GetProjects(string domain, string user) {
            return base.Channel.GetProjects(domain, user);
        }
        
        public System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> GetProjectsAsync(string domain, string user) {
            return base.Channel.GetProjectsAsync(domain, user);
        }
        
        public Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse SyncSearchSets(string userTradeAbbr, int clashMatrixId, string[] definedSearchSets) {
            return base.Channel.SyncSearchSets(userTradeAbbr, clashMatrixId, definedSearchSets);
        }
        
        public System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> SyncSearchSetsAsync(string userTradeAbbr, int clashMatrixId, string[] definedSearchSets) {
            return base.Channel.SyncSearchSetsAsync(userTradeAbbr, clashMatrixId, definedSearchSets);
        }
        
        public Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse GetClashTests(int clashMatrixId) {
            return base.Channel.GetClashTests(clashMatrixId);
        }
        
        public System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> GetClashTestsAsync(int clashMatrixId) {
            return base.Channel.GetClashTestsAsync(clashMatrixId);
        }
        
        public Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse SyncClashResults(int clashMatrixId, Clash_Management_System_Navisworks_Addin.WebService.ClashResultSyncRequest[] updateRequests) {
            return base.Channel.SyncClashResults(clashMatrixId, updateRequests);
        }
        
        public System.Threading.Tasks.Task<Clash_Management_System_Navisworks_Addin.WebService.ServiceResponse> SyncClashResultsAsync(int clashMatrixId, Clash_Management_System_Navisworks_Addin.WebService.ClashResultSyncRequest[] updateRequests) {
            return base.Channel.SyncClashResultsAsync(clashMatrixId, updateRequests);
        }
    }
}
